server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    password: admin
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

okta:
  oauth2:
    issuer: https://dev-94646799.okta.com/oauth2/default
    audience: api://default
