spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MicroService


server:
  port: 8082

okta:
  oauth2:
    issuer: https://dev-94646799.okta.com/oauth2/default
    audience: api://default